name: "Build"

on:
  push:
    paths_ignore:
      - '**/*.md'
  pull_request:
    paths_ignore:
      - '**/*.md'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set dist name
        run: |
          echo "distdir=${{ github.workspace  }}/bin" >> "$GITHUB_ENV"

      - name: Build project
        run: |
          dotnet publish -c Release -o ${{ env.distdir }} --runtime win-x64 ${{ github.workspace  }}/Spz.NET/
          dotnet publish -c Release -o ${{ env.distdir }} --runtime linux-x64 ${{ github.workspace  }}/Spz.NET/
          dotnet publish -c Release -o ${{ env.distdir }} --runtime win-arm64 ${{ github.workspace  }}/Spz.NET/
          dotnet publish -c Release -o ${{ env.distdir }} --runtime linux-arm64 ${{ github.workspace  }}/Spz.NET/
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: spz-net
          path: ${{ env.distdir }}
