name: "Build"

on:
  push:
    paths_ignore:
      - '**/*.md'
  pull_request:
    paths_ignore:
      - '**/*.md'


jobs:
  build:
    strategy:
      matrix:
        osver: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.osver }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set dist name
        run: |
          if ${{ matrix.osver == 'ubuntu-24.04-arm' }}; then
            echo "distname=spz-net-arm" >> "$GITHUB_ENV"
          else
            echo "distname=spz-net" >> "$GITHUB_ENV"
          fi
          echo "distdir=${{ github.workspace  }}/bin" >> "$GITHUB_ENV"

      - name: Build project
        run: |
          dotnet publish -c Release -o ${{ env.distdir }} ${{ github.workspace  }}/Spz.NET/
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.distname }}
          path: ${{ env.distdir }}
